src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Checkings;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Checkings\Email(message: 'Veuillez rentrer une adresse mail valide.')]
    #[Checkings\NotBlank(message: 'Veuillez renseigner une adresse')]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Checkings\Length( min: 5, minMessage: 'Le mot de passe doit faire au moins 5 caractères')]
    #[Checkings\NotBlank(message: 'Veuillez renseigner un mot de passe')]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    #[Checkings\NotBlank(message: 'Veuillez renseigner votre prénom')]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    #[Checkings\NotBlank(message: 'Veuillez renseigner votre nom')]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Question::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255)]
    #[Checkings\Url(message: 'Votre image doit provenir d\'une url')]
    private ?string $picture = null;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setUser($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getUser() === $this) {
                $question->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this-> firstname . ' ' . $this->lastname;
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Repository\QuestionRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ForumController extends AbstractController
{
    #[Route('/forum', name: 'forum')]
    public function index(QuestionRepository $questionRepository): Response
    {
        $questions = $questionRepository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('forum/index.html.twig', [
            'questions' => $questions,
        ]);
    }
}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forum{% endblock %}

{% block body %}
    {% include ('home/partials/_nav.html.twig') %}
    
    
<div class="forum_container container-fluid">
    <div class="row">
    {% include ('home/partials/_sidebar.html.twig') %}

<ul class="col-9 mt-3 text-light">
    {% for question in questions %}
        <a href="{{path('question_show', { id: question.id}) }}" class="d-flex text-decoration-none">
            <div class=" topic_container border col-12 mt-3 d-flex flex-column rounded">
                <div>
                    <div class="row">
                      <!-- <a class="test" href="{{ path('user', {id: question.user.id}) }}"> -->
                        <img class="ask_question_avatar mb-2 col-4" src=" {{question.user.picture}}"/>
        
                        <h4 class="py-2 col-8">{{question.title}} </h4>
                    </div>
                    <p> {{question.content}} <p>
                </div>
                    <p class="timer_topic"> Question posée par {{ question.user.fullname }} <span> {{question.createdAt | ago(locale="fr")}} </span></p>
                <div class="d-flex  align-items-between">
                    <div class="d-flex justify-content-around py-2 col-4">
                        <i class = "fas fa-arrow-up mt-1"> </i>
                        <i class= "fas fa-arrow-down mt-1 px-2 "> </i>
                        <i class="far fa-comment px-1 mt-1"></i>
                        <p class=""> {{question.answers }} réponse(s) </p>
                        <i class="fa-solid fa-share-nodes mt-1"></i>
                        <p> 0 partage </p>
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    </ul>
    </div>
</div>
{% include ('home/partials/_footer.html.twig') %}

{% endblock %}